name: car_cutter_test
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  json_serializable: ^6.11.2
  dio: ^5.9.0
  drift: ^2.30.0
  drift_flutter: ^0.2.8
  go_router: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  riverpod_generator: ^3.0.3
  drift_dev: ^2.30.0

flutter:
  uses-material-design: true
